version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=development
